services:
  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stickersweb
    restart: always
###> doctrine/doctrine-bundle ###

volumes:
  mysql-data: ###< doctrine/doctrine-bundle ###
